### ISSUE TITLE
Create Uniform way of defining metric Desc

### ISSUE THREAD

**Issue by logyball** [grafana/cloudcost-exporter#222]
[Based on this comment.](https://github.com/grafana/cloudcost-exporter/pull/213#discussion_r1656960493)

We have _very_ similar metrics defined across cloud providers.  They have the same suffix and help text.  We should create a way to uniformly change their descriptions using a re-usable function, or something like that.

**Comment by ohyesgocool** [comment]
Hi Can i pick this issue ? You can assign it to me

**Comment by Pokom** [comment]
Hi @ohyesgocool, you're more then welcome! Let me know if there's enough information here for you to go off of. If you need a bit faster communication, you can reach out in our public slack channel: https://grafana.slack.com/archives/C064EMEB4E6
