### ISSUE TITLE
Implement persistent volumes in AWS

### ISSUE THREAD

**Issue by Pokom** [grafana/cloudcost-exporter#235]
The primary goal is to export a metric that calculates the hourly cost of each persistent volume within our EKS clusters. The exported metric should align with our existing metrics(`cloudcost_aws_eks_persistent_volume_dollars_per_hour`). 

There's really two parts:
1. Generate a Pricing Map that enables searching by region and storage class
2. List out EBS volumes 

There should be the following labels:
- cluster
- namespace
- persistentvolume
- storage_class
- status(in use or not)

@paulajulve had pointed out the cluster label _may_ not be possible to derive from the API response. If that's the case, then we need to consider how we can join against existing kube state metrics to derive the cluster name.

**Comment by Pokom** [comment]
Most of the functionality is implemented with tweaks to naming and what not. The main thing is adding tests, specifically for the `Collect` method, is tightly coupled to the compute module. 

@Pokom will take a look to see if we can split out the collect method in such a way where you can create a method that encapsulates the logic into a testable method.

**Comment by Pokom** [comment]
Currently working to offload processing of the volumes to a background goroutine for performance reasons. @paulajulve will close this out and follow up with another issue that details the performance problems and track the work there.

**Comment by paulajulve** [comment]
Next steps:
- performance implementations will continue [here](https://github.com/grafana/cloudcost-exporter/issues/274)
- I've not yet fully validated the numbers on the metrics we're emitting, but that'll continue as a separate work stream too, as I work to switch our own usage of Open Cost for EBS volumes to these ones.
